# Site settings
name: Augury One
url: https://augury.one
meta_description: "Deliver safer software."

# Section settings
sections:
  intro:
    title: Augury One
    tagline: >
      Deliver safer software.
  services:
    title: Services
    description: >
      Augury One is a boutique software security firm that specializing in Code Review, Software Vulnerability Intelligence, and Emergency Response with a goal of enabling organizations to deliver safe software.
    list:
      - title: "Code Review"
        description: >
          On-demand code review embeds expert security engineers into the software development lifecycle, supporting engagements initiated directly within GitHub. By partnering directly with software engineers, Augury One security engineers proactively find, triage, and advise on mitigation and remediation of the vulnerabilities in software as it’s developed.
        icon: code-fork
      - title: "Software Vulnerability Intelligence"
        description: >
          Software vulnerability intelligence enhances vulnerability management capabilities by turning identifiable disclosures into advisories. Augury One eliminates the need to spend time gathering intelligence and performing technical analysis through timely curated advisories, enriched with detailed root cause analysis, mitigations, remediations, and community knowledge.
        icon: shield
      - title: "Emergency Response"
        description: >
          When a vulnerability in an organization's software is suspected or known to be exploited, Augury One will be there. We offer timely and direct support for core incident response activities, accelerating and ensuring the path to resolution is correct and complete through vulnerability identification and resolution verification.
        icon: life-buoy

  platform:
    title: Platform Features
    description: >
      Augury One breaks away from the traditional consultancy model, offering continuous service delivery through an immediate and on-demand service model allowing organizaitons to access security expertise when it's needed most, 24/7.
    subsections:
    - title: Code Review
      features:
        - name: Native GitHub Integration
          description: >
            When merging a feature or branch, engineers can request code reviews directly from GitHub Issues and Pull Requests.
          icon: github
        - name: Scope-guided Reviews
          description: >
            Engineer-guided reviews are scoped collaboratively to ensure timely, cost-effective coverage.
          icon: crosshairs
        - name: Immediate Vulnerability Delivery
          description: >
            Each vulnerability identified during a code review is disclosed immediately, allowing for prompt mitigation and remediation instead of having to wait for a final report. 
          icon: fast-forward
        - name: Built-in Collaboration
          description:
            Whether engineers are in GitHub or the Augury One platform, they can engage directly with their reviewer on identified vulnerabilities, proposed mitigations, and remediations.
          icon: comments-o
    - title: Software Vulnerability Intelligence
      features:
        - name: Timely Advisories
          description: >
            Augury One will issue curated and digestible advisories for emerging software security vulnerabilities, regardless of CVE issuance.
          icon: clock-o
        - name: Advisory Update Notifications
          description: >
            Organizations can subscribe to updates on advisory changes to stay informed about new information and modifications.
          icon: rss
        - name: Root-cause Analysis and Detection Guidance
          description: >
            Each advisory includes detailed information allowing organizations to better understand the technical details and search for related abuses within their organization.
          icon: search
        - name: Mitigation and Remediation
          description: >
            When official remediation guidance is unable to be followed  (e.g. version-locked), Augury One provides direction on available mitigations, helping organizations reduce their risk of exposure until full remediation can be achieved.
          icon: wrench
        - name: Community Discussions
          description: >
            Augury One organizations can discuss each advisory through a private discussion section within the Augury One platform, benefiting from and contributing to the community knowledge of advisory details.
          icon: users
    - title: Emergency Response
      features:
        - name: Vulnerability Identification
          description: >
            Augury One will help identify suspected software vulnerabilities during an incident, accelerating the pursuit of mitigation and remediation.
          icon: eye
        - name: Resolution Verification
          description: >
            When a mitigation or remediation is implemented, Augury One will provide guidance and testing through analysis of the remediation, relative to the identified vulnerability, helping ensure it is correct and complete.
          icon: fire-extinguisher
        - name: Embedded Response Team
          description: >
            The Augury One response team embeds directly within an organization's incident response structure, augmenting and extending existing staff capabilities.
          icon: plus-square-o
        - name: Timely On-Call Support
          description: >
            Augury One is available by call, text or email when needed. An on-call rotation is maintained to ensure each organization has appropriate and timely support when an incident may arise.
          icon: phone
  pricing:
    title: "Pricing"
    description:
      We believe in price transparency and fairness. Regardless of organization size,
      our advertised prices are what are paid. We do not negotiate.
      Although our billing model is slightly different within our platform, we have 
      translated this to hourly rates to make our offerings easy to reason about. 
    subsections:
      - title: Code Review
        on_demand: $600/hr
        reserved: $400/hr
      - title: Vulnerability Triage
        on_demand: $500/hr
        reserved: $400/hr
      - title: Emergency Response
        on_demand: $1125/hr
        reserved: $750/hr
  about:
    title: About
    description: >
      Augury One was founded to improve the state of software security, 
      lowering the barrier of entry to security services. Staffed by expert 
      software security engineers, Augury One provides organizations continous 
      security advisory and engineering support, augmenting and extending 
      existing organization capabilities.
  contact:
    title: "contact"
    description: >
      Want to know more? Lets chat.
    email: inquiry@augury.one
    social:
      - title: twitter
        url: https://x.com/augury_one
      - title: github
        url: https://github.com/AuguryOne
  footer:
    content: Augury One

# Color settings (hex-codes without the leading hash-tag)
css:
  color:
    primary-dark: '#000000'
    links:  rgb(147 197 253);

# Build settings
markdown: kramdown
permalink: pretty
