# Site settings
name: Shh Services
url: https://shh.services
meta_description: ""

# Section settings
sections:
  intro:
    title: Shh
    tagline: >
      Spend less. Secure more.
  services:
    title: Services
    description: >
      
    list:
    - title: "Scoping"
      description: >
        Don't know what to prioritize in a security review? We will work with
        you to tailor a scope that prioritizes your security concerns.
      icon: crosshairs
    - title: "Vendor alignment"
      description: >
        Have you defined your scope but don't know which vendor to choose? We
        can help you choose the perfect vendor to perform the assessment.
      icon: align-center
    - title: "Finding prioritization"
      description: >
        Have you completed an assesment but don't know how to proceed? We can
        help you review the findings and build a plan for remediation.
      icon: list-ol
    - title: "Deliverable management"
      description: >
        Not sure how to share the results of an assessment? We work with our
        clients and the vendor to help properly convey findings and remediations.
      icon: flag-checkered
  affiliates:
    title: Trusted vendors
    description: >
      While <strong>Shh</strong> is open to working with any vendor at the
      client's request, we also curate a set of trusted vendors known to provide
      excellent results in their area of expertise. We work directly with these
      vendors on our client's behalf to shorten the project scheduling process
      and ensure deliverables are tailored to our client's needs.
    invitation: >
      Interested in becoming a trusted vendor? <a class="page-scroll"
      href="#contact">We would love to chat</a>.
    vendors:
  about:
    title: About
    description: >
      <strong>Our objective is to keep our clients safe.</strong> Shh was
      founded to improve the process of performing 3rd party security assessments
      by pairing our clients with the best vendors for their needs. We do the
      heavy lifting, identifying each vendor's strengths so our clients can
      engage them with the appropriate scope and budget. As a result our clients
      get better results, and vendors get the work they prefer.
  contact:
    title: "contact"
    description: >
      Want to know more? Lets chat.
    email: inquiry@shh.services
    social:
      - title: twitter
        url: https://twitter.com/shhservices
      - title: github
        url: https://github.com/shh-services
  footer:
    content: Shh Services

# Color settings (hex-codes without the leading hash-tag)
css:
  color:
    primary-dark: '#000000'
    links: '#219ab3'

# Build settings
markdown: kramdown
permalink: pretty
