# Site settings
name: Augury One
url: https://augury.one
meta_description: "Deliver safer software."

# Section settings
sections:
  intro:
    title: Augury One
    tagline: >
      Deliver safer software.
  services:
    title: Services
    description: >
      Augury One specializes in software security advisory services across
      Emergency Response, Code Review, and Vulnerability Triage.
    list:
    - title: "Emergency Response"
      description: >
        We augment your software security incident response process, helping to
        ensure exploitable vulnerabilities are properly investigated and remediated
        when identified.
      icon: flash
    - title: "Code review"
      description: >
        Throughout the software development lifecycle, we continuously review 
        the code written by your organization to identify exploitable vulnerabilities.
      icon: terminal
    - title: "Vulnerability Triage"
      description: >
        We analyze publicly disclosed software vulnerabilities, performing root cause 
        analysis and developing detections, remediations, and reproductions as part of 
        the triage process.
      icon: bug

  platform:
    title: Platform Features
    description: >
      The Augury One platform streamlines the engagement model for security
      advisory services. Once integrated, our customers have immediate
      access to on-demand advisory resources across all service offerings, 
      and can configure the platform's use for their organization.
    subsections:
    - title: Code Review
      features:
        - name: Version control integration
          description: >
            Any engineers can request a security review directly from their version
            control system.
          icon: github
        - name: Scope-guided engineering resources
          description:
            Your engineers provide the scope for each review. We triage these requests to
            ensure appropriate and consistent staffing each time.
          icon: crosshairs
        - name: Customer-specified priority
          description: >
            The requestor sets the appropriate priority for the review. We use this 
            to ensure SLAs are met.
          icon: sort-numeric-asc
        - name: Share findings
          description:
            Reviews and their associated findings can be shared, allowing for 
            public-facing communication of any identified vulnerabilities that may result 
            from a code review.
          icon: share
    - title: Vulnerability Triage
      features:
        - name: Central Advisory Directory
          description: >
            From cloud CI breach advisories, to the latest software vulnerabilities,
            we organize advisories in a central and searchable location.
          icon: folder-open
        - name: Root Cause
          description: >
            We review each advisory to provide appropriate root cause context,
            and verify the impact it could have to affected systems.
            systems.
          icon: search
        - name: Detections
          description: >
            For each triaged advisory, we provide guidance on how to detect affected 
            systems, as well how to search for prior exploitation within the affected
            system.
          icon: eye
        - name: Mitigations & Remediation
          description: >
            When possible, we provide detailed guidance on how to ensure mitigations
            and remediations are implemented for affected systems.
          icon: wrench
    - title: Emergency Response
      features:
        - name: Embedded Response Team
          description: >
            Our response team embedds directly with your organization's response, providing
            advisory services and engineering support throughout the duration of the event.
          icon: group
        - name: Impact Investigations
          description: >
            Embedded engineers work with responders to identify evidence of impact, helping
            to advise next steps.
          icon: fire
        - name: Fix Verification
          description: >
            When a mitigation or remediation is implemented, we help verify it is correct and 
            complete.
          icon: fire-extinguisher
        - name: Direct Engagement
          description: >
            Page us when you need us - we maintain an on-call rotation to ensure your 
            organization has appropriate support whenever an emergency may arise.
          icon: phone
  pricing:
    title: "Pricing"
    description:
      We believe in price transparency and fairness. Regardless of the size of your 
      organization, our advertised prices are what you will pay. We do not negotiate.
      Although our billing model is slightly different within our platform, we have 
      translated this to hourly rates to make our offerings easy to reason about. 
    subsections:
      - title: Code Review
        on_demand: $600/hr
        reserved: $400/hr
      - title: Vulnerability Triage
        on_demand: $500/hr
        reserved: $400/hr
      - title: Emergency Response
        on_demand: $1125/hr
        reserved: $750/hr
  about:
    title: About
    description: >
      <strong>Our objective is to keep our clients safe.</strong> Augury One
      was founded to improve the state of software security by lowering the
      barrier of entry to security services. Instead of providing
      point-in-time assessments, Augury One provides our customers continous
      security advisory and engineering support, augmenting their existing
      engineering staff.
  contact:
    title: "contact"
    description: >
      Want to know more? Lets chat.
    email: inquiry@augury.one
    social:
      - title: twitter
        url: https://twitter.com/shhservices
      - title: github
        url: https://github.com/AuguryOne
  footer:
    content: Augury One

# Color settings (hex-codes without the leading hash-tag)
css:
  color:
    primary-dark: '#000000'
    links:  rgb(147 197 253);

# Build settings
markdown: kramdown
permalink: pretty
