# Site settings
name: Shh Services
url: https://shh.services
meta_description: ""

# Section settings
sections:
  intro:
    title: Shh
    tagline: "todo"
  services:
    title: Services
    description: "todo"
    list:
    - title: "Scoping"
      description: "Service description"
      icon: crosshairs
    - title: "Vendor alignment"
      description: "Another service"
      icon: align-center
    - title: "Deliverable management"
      description: "Another service"
      icon: flag-checkered
    - title: "Finding prioritization"
      description: "another service"
      icon: bug
  about:
    title: About
    description: "todo"
  contact:
    title: "contact"
    description: "todo"
    email: inquiry@shh.services
    social:
      - title: twitter
        url: https://twitter.com/shhservices
      - title: github
        url: https://github.com/shh-services
  footer:
    content: Shh Services

# Color settings (hex-codes without the leading hash-tag)
css:
  color:
    primary-dark: '#000000'
    links: '#219ab3'

# Build settings
markdown: kramdown
permalink: pretty
