# Site settings
name: Shh Services
url: https://shh.services
meta_description: "Deliver safer software."

# Section settings
sections:
  intro:
    title: Shh
    tagline: >
      Deliver safer software.
  services:
    title: Services
    description: >
      Shh Services specializes in three arieas: Rapid Risk
      Assessment, Code Review, and Software Vulnerability Management. These
      services are available through a tailored platform allowing customers a
      configurable pricing and avaialability model for security engineering
      resources specializing in each of our service offerings.
    list:
    - title: "Rapid Risk Assessment"
      description: >
        Rapid risk assessments led by experienced security engineers
        help to identify high-risk software components for enhanced research and
        review before they are exploited and abused.
      icon: crosshairs
    - title: "Code review"
      description: >
        Code review led by experienced software security engineers
        identifies flaws and prevents exploitation as software is
        developed over time.
      icon: align-center
    - title: "Software Vulnerability Management"
      description: >
        Security engineers are available 24/7 to assist with the
        intake, triage and remediation of vulnerabilities found within customer
        codebases. 
      icon: bug

  platform:
    title: Platform Features
    description: >
      Our platform allows for streamlined on-boarding, only
      requiring our customers to install a version control system provider
      integration to get started. Once integrated, our customers have immediate
      access to on-demand security engineering resources across all of our
      service offerings, and are able to configure how they are used by their
      organization.
    subsections:
    - title: Continuous Code Review
      features:
        - name: Native version control provider integration
          description: >
            Native integration allows for faster time-to-review, and simple
            onboarding of services. All feedback within our platform can be
            forwarded to the version control provider, such as GitHub issues,
            discussions, and pull requests. 
          icon: github
        - name: Scope-guided engineering resources
          description:
            Our customers define scope for each review, ensuring appropriate
            staffing every time. Don’t want to manually approve scope every
            time? Create pre-configured scopes for common requests.
          icon: users
        - name: Customer-specified availability
          description: >
            Security engineers can be requested for reviews as-needed or placed in
            a dedicated reserve. When problems are arise, the assigned engineers will
            work with you to identify a solution and ensure remediation. 
          icon: calendar
        - name: Avoid unsafe changes
          description: >
            Concerned about merging dangerous code? Our provider integrations
            allow you to configure merge requirements, allowing you to balance
            security and release velocity.
          icon: code-fork
    - title: Software Vulnerability Management
      features:
        - name: Vulnerability intake
          description: >
            Stop fussing with bug bounty program management. Our engineers staff
            a 24/7 on-call to handle responsible disclosure on your behalf,
            helping to reproduce and confirm the validity of reported findings.
          icon: bug
        - name: Root cause analysis
          description: >
            Once a vulnerability has been identified, our engineers perform root
            cause analysis to identify the implementation or design flaw
            allowing the vulnerability to exist.
          icon: search
        - name: Patching and remediation
          description: >
            Our engineers work directly with our customer's engineering teams to
            patch and remediate identified vulnerabilities. Paired with our code
            review offerings, this helps to prevent vulnerability regressions.
          icon: code
        - name: Detection engineering
          description: >
            After remediation is complete, our engineers help to engineer
            signatures to detect the exploitation of the vulnerability in the
            past, present, and future.
          icon: shield
  about:
    title: About
    description: >
      <strong>Our objective is to keep our clients safe.</strong> Shh Services
      was founded to improve the state of software security by lowering the
      barrier of entry to traditionally expensive services. Instead of providing
      point-in-time assessments, Shh Services provides our customers continous
      security advisory and engineering support, augmenting their existing
      engineering staff.
  contact:
    title: "contact"
    description: >
      Want to know more? Lets chat.
    email: inquiry@shh.services
    social:
      - title: twitter
        url: https://twitter.com/shhservices
      - title: github
        url: https://github.com/shh-services
  footer:
    content: Shh Services

# Color settings (hex-codes without the leading hash-tag)
css:
  color:
    primary-dark: '#000000'
    links: '#cfa7a7'

# Build settings
markdown: kramdown
permalink: pretty
